# Generated by Django 2.2 on 2022-03-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20220316_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='timing',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
