# Generated by Django 2.2 on 2022-03-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20220316_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='booked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
