# Generated by Django 2.2 on 2022-03-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20220316_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetail',
            name='driver_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='busdetail',
            name='mobile',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(blank=True, max_length=50, null=True)),
                ('marked', models.BooleanField(blank=True, default=False, null=True)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.BusDetail')),
            ],
        ),
    ]
