# Generated by Django 2.2 on 2022-03-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_busdetail_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='marked_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
