# Generated by Django 2.2 on 2022-03-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_route_marked_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetail',
            name='nos',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busdetail',
            name='rem',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
