# Generated by Django 2.2 on 2022-03-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20220330_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetail',
            name='nos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='busdetail',
            name='rem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
