# Generated by Django 2.2 on 2022-03-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20220330_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='booked',
        ),
    ]
