# Generated by Django 2.2 on 2022-03-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_seat_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='price',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='busdetail',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
