# Generated by Django 2.2 on 2022-03-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20220330_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busdetail',
            name='price',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='amount',
        ),
    ]
